### ISSUE TITLE
How to make a simple red cube?

### ISSUE THREAD

**Issue by cmg2** [apbodnar/FSPT#10]
I'm trying to rever-engineer this esotheric scene definition language and so far was able to create a pitch-black cube. How do I give it a color?

**Comment by cmg2** [comment]
Here's my naive attempt to make this cube:

```
v 0 0 0
v 1 0 0
v 1 1 0
v 0 1 0
v 0 0 1
v 1 0 1
v 1 1 1
v 0 1 1

f 1 2 3
f 1 3 4
f 5 6 7
f 5 7 8
f 1 2 6
f 1 5 6
f 3 4 7
f 4 7 8
f 1 4 5
f 4 5 8
f 2 3 6
f 3 6 7
```

```json
{
  "environment": "environment/autumn_meadow_2k.RGBE.PNG",
  "environmentTheta": 1.66,
  "cameraPos": [-0.751,0.665,1.820],
  "cameraDir": [0.304,-0.489,-0.818],
  "props": [
    {
      "path": "asset_packs/misc/cube_simple.obj",
      "scale": 0.35,
      "rotate": [{"angle": 0, "axis": [0,0,1]}],
      "translate": [0.1, -0.7, 0],
      "diffuse": [1, 1, 1],
      "emittance": [0, 0, 0],
      "metallicRoughness": [0, 0.1, 0],
      "ior": 1.4,
      "normals": "smooth"
    }
  ]
}
```

**Comment by apbodnar** [comment]
You've actually found a fun bug where using no texture at all causes it to pack a 0x0 texture atlas, which obviously won't work.  I'll push up a fix.  Your scene looks mostly correct. I think you want to change "smooth" to "flat" (or "mesh if your obj has `vn` rules")

Thanks

**Comment by apbodnar** [comment]
Also, to make it a chosen color, use "diffuse": <some 3 element array>   like [1, 0, 0] for red
