### ISSUE TITLE
How to apply the glass material to the bunny.json scene?

### ISSUE THREAD

**Issue by cmg2** [apbodnar/FSPT#11]

**Comment by apbodnar** [comment]
To make an object translucent, you'll need to set `"dielectric": <some non-zero value>,`.  This feature is still pretty hacky and will misbehave if your mesh doesn't have a closed surface.  The value you assign to `"dielectric"` is an attenuation term, so a higher value will absorb more light as a function of the refraction path length.  The color absorbed is (1 - diffuse) which means that the transmitted color is the diffuse color.
![bunny](https://user-images.githubusercontent.com/2200441/82742436-eda1d680-9d12-11ea-9780-ce6456e6562e.png)
