### ISSUE TITLE
Links to new samples?

### ISSUE THREAD

**Issue by knightcrawler25** [apbodnar/FSPT#2]
Some of the new samples look really neat! Is there a way I can play with these? I see only 3 links to the older demos in the readme.

**Comment by apbodnar** [comment]
HI! Thanks for the issue. Making new interesting demos is my priority.  I removed most assets from the repo because doing so would mean they could be requested every time a user loads a demo, and I'm wary of github getting mad at me for hosting gigabytes of traffic on my github page.  But, I'll definitely host _something_ interesting for people to play with.

**Comment by knightcrawler25** [comment]
Sure! No problem. Also, what kind of bvh and traversal are you using? And what's the performance like? I'm a hobbyist and working on a fragment shader based path tracer too during my spare time and I tried a couple of things like rendering at quarter res during preview and also tiled rendering but performance still feels a bit inadequate for somewhat larger scenes. Some of the faster traversal kernels from RadeonRays/Nvidia use CUDA/OpenCL for better control over threads but moving to that is a last resort. Any ideas? Suggestions? Thanks :)

**Comment by apbodnar** [comment]
For construction, I'm using a fairly naive SAH based BVH. From traversal, I'm currently using a variation of a purely stackless traversal algorithm (http://www.sci.utah.edu/~wald/Publications/2011/StackFree/sccg2011.pdf). I've experimented with a short stack version, but had a 50% performance degradation. I didn't investigate too deeply into the cause I'm not sure how to gauge performance.  The lack of scheduling in a fragment shader plus no multi-gpu in webgl means it'll probably always have a fraction of the performance of a GPGPU version.  I might be referencing your light sampling and IBL importance sampling code soon though 😜

**Comment by knightcrawler25** [comment]
I've tried multiple-threaded BVH traversal from (https://arxiv.org/pdf/1505.06022.pdf) quite a while ago but used a BVH with naive median splits so did not notice much difference in performance. Same thing being used here: (http://webraytracer.alexandra.dk). Would probably give it a try again since I've switch to using an SBVH. Also, you might want to use the dev branch for the importance sampling code since i'll be fixing a couple of issues with the pdf calculation when I get some free time this weekend :)
